version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: Install awscli
          command: sudo apt-get install awscli
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: make test
      - run:
          name: build
          command: make build
      - deploy:
          name: Deploy to production if master
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  make build-production deploy
              fi

